import { VersionDelta } from '../VersionInfo.ts';

export default {
	publicBuiltins: [
		["Array", "isArray"],
		["Date", "UTC"],
		["Date", "now"],
		["Date", "parse"],
		["JSON", "parse"],
		["JSON", "stringify"],
		["Math", "abs"],
		["Math", "acos"],
		["Math", "asin"],
		["Math", "atan"],
		["Math", "atan2"],
		["Math", "ceil"],
		["Math", "cos"],
		["Math", "exp"],
		["Math", "floor"],
		["Math", "hypot"],
		["Math", "imul"],
		["Math", "log"],
		["Math", "max"],
		["Math", "min"],
		["Math", "pow"],
		["Math", "round"],
		["Math", "sin"],
		["Math", "sqrt"],
		["Math", "tan"],
		["Math", "trunc"],
		["Object", "create"],
		["Object", "defineProperties"],
		["Object", "defineProperty"],
		["Object", "freeze"],
		["Object", "getOwnPropertyDescriptor"],
		["Object", "getOwnPropertyNames"],
		["Object", "getPrototypeOf"],
		["Object", "isExtensible"],
		["Object", "isFrozen"],
		["Object", "keys"],
		["Object", "seal"],
		["String", "fromCharCode"],
	],
} satisfies VersionDelta;